#!/bin/bash
rm -rf LED_Cube_Simulator.app

install_name_tool -change /Library/Frameworks/Python.framework/Versions/3.7/Python @rpath/Python.framework/Versions/3.7/Python LED_Cube_Simulator/DerivedData/Build/Products/Release/LED_Cube_Simulator.app/Contents/MacOS/LED_Cube_Simulator

mkdir -p LED_Cube_Simulator/DerivedData/Build/Products/Release/LED_Cube_Simulator.app/Contents/Frameworks/Python.Framework/Versions

cp -r /Library/Frameworks/Python.framework/Versions/3.7 LED_Cube_Simulator/DerivedData/Build/Products/Release/LED_Cube_Simulator.app/Contents/Frameworks/Python.Framework/Versions/.

#cp -r /Library/Frameworks/Python.framework/Versions/3.7/Python LED_Cube_Simulator/DerivedData/Build/Products/Release/LED_Cube_Simulator.app/Contents/Frameworks/Python.Framework/.

#cp -r /Library/Frameworks/Python.framework/Versions/3.7/Resources LED_Cube_Simulator/DerivedData/Build/Products/Release/LED_Cube_Simulator.app/Contents/Frameworks/Python.Framework/.

rm -rf LED_Cube_Simulator/DerivedData/Build/Products/Release/LED_Cube_Simulator.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test

rm -rf LED_Cube_Simulator/DerivedData/Build/Products/Release/LED_Cube_Simulator.app/Contents/Frameworks/Python.framework/Versions/3.7/share/doc

otool -L LED_Cube_Simulator/DerivedData/Build/Products/Release/LED_Cube_Simulator.app/Contents/MacOS/LED_Cube_Simulator

mv LED_Cube_Simulator/DerivedData/Build/Products/Release/LED_Cube_Simulator.app .

rm -rf LED_Cube_Simulator.app/Contents/Resources/c++/build 
rm -rf LED_Cube_Simulator.app/Contents/Resources/c++/*.txt 
rm -rf LED_Cube_Simulator.app/Contents/Resources/c++/*.cpp
rm -rf LED_Cube_Simulator.app/Contents/Resources/c++/*.backup
rm -rf LED_Cube_Simulator.app/Contents/Resources/c++/*.h
rm -rf LED_Cube_Simulator.app/Contents/Resources/matlab/*.cpp
rm -rf LED_Cube_Simulator.app/Contents/Resources/python/*.backup

mkdir LED_Cube_Simulator.app/Contents/Resources/examples
mv LED_Cube_Simulator.app/Contents/Resources/python LED_Cube_Simulator.app/Contents/Resources/examples/.
mv LED_Cube_Simulator.app/Contents/Resources/c++ LED_Cube_Simulator.app/Contents/Resources/examples/.
mv LED_Cube_Simulator.app/Contents/Resources/matlab LED_Cube_Simulator.app/Contents/Resources/examples/.
mv LED_Cube_Simulator.app/Contents/Resources/resources LED_Cube_Simulator.app/Contents/Resources/examples/.



